### PR TITLE
bypass certificate verify

### PR DESCRIPTION
**Pull request by Tianhao-Gu**

### CODE REVIEW

**Comment by Tianhao-Gu** [comment]
@MrCreosote certificate chain is broken somehow.

**Comment by MrCreosote** [comment]
Hmm, this makes us vulnerable to MITM attacks. Is there a reason we can't just install the missing certs in the dockerfile? @scanon @sychan what's your opinion?

JIRA ticket is here: https://kbase-jira.atlassian.net/browse/TASK-892

**Comment by MrCreosote** [comment]
I jumped into @scanon and @sychan 's office and they agree we should just update the certs if we can. @sychan is dredging his memory for the process to do that.

**Comment by Tianhao-Gu** [comment]
👍 👍

**Comment by Tianhao-Gu** [comment]
@MrCreosote This should fix the ssl issue.

**Comment by MrCreosote** [comment]
All tests now pass.

**Pull request merged**
